name: Pipeline
on: [push, pull_request]



jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set locale
        run: sudo locale-gen pt_BR.UTF-8

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.6

      - name: Poetry Install
        run: pip install poetry
          
      - name: Install Dependencies
        run: |
          poetry install --without doc
          poetry run playwright install

      - name: Run Tests
        run: poetry run task test --cov-report=xml

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true